"""
modules/predictor.py
====================
The single, authoritative inference module for Neuro-Screen.

Every prediction in the app — the Quick check-in form, the Results page and
the conversational assistant — flows through :func:`predict`. There is no
fallback heuristic anywhere else: if the trained artifacts are missing,
:func:`models_available` returns ``False`` and :func:`predict` raises
:class:`ModelNotReadyError` rather than fabricating a score.

Prediction path (identical to Thesis3.ipynb):

  1. Answers are aligned to the exact training feature columns; anything
     missing becomes the learned ``"Missing"`` category.
  2. CatBoost scores the raw categorical frame (native categorical handling)
     and contributes per-instance SHAP values.
  3. The ANN scores the one-hot encoded + age-scaled frame.
  4. ``P_hybrid = (P_catboost + P_ann) / 2``; prediction = ``P_hybrid >= 0.5``.

Artifacts (generated by ``scripts/train_models.py``, see ``config.ARTIFACTS``):

* ``catboost_model.cbm``          — trained CatBoost classifier
* ``ann_model.pt``                — trained ANN checkpoint (PyTorch)
* ``scaler.pkl``                  — StandardScaler fitted on age
* ``label_encoder.pkl``           — category vocabulary learned by the model
* ``feature_columns.pkl``         — one-hot column layout from training
* ``preprocessing_pipeline.pkl``  — bundled pipeline metadata + vocab
* ``metadata.json``               — feature order, cat features, threshold
* ``eval_metrics.json`` / ``roc_data.json`` — held-out evaluation

Models are imported lazily so the app still runs (and shows a clear status
banner) before CatBoost/PyTorch are installed or the models are trained.
"""

from __future__ import annotations

import pickle
from dataclasses import dataclass
from typing import Optional

import numpy as np
import pandas as pd

import config
from modules.core.preprocessing import (
    MISSING_TOKEN,
    build_ann_frame,
    to_tensor_float,
)
from modules.core.risk import (
    FeatureDriver,
    RiskResult,
    readable_driver,
    severity_for,
)


class ModelNotReadyError(RuntimeError):
    """Raised when predict() is called before the trained artifacts exist."""


@dataclass
class PredictorBundle:
    """Loaded model artifacts, held in a module-level cache."""

    catboost: object
    ann: "CognitiveImpairmentANN"
    scaler: object
    ann_columns: list[str]
    meta: dict
    vocab: dict = None


_cache: Optional[PredictorBundle] = None

# Artifacts required for a real prediction.
_REQUIRED = ("catboost", "ann", "scaler", "feature_columns", "meta")


# ------------------------------------------------------------------
# Availability + loading (lazy, cached)
# ------------------------------------------------------------------
def models_available() -> bool:
    """True when all artifacts needed for a real prediction are present."""
    return all(config.ARTIFACTS[name].exists() for name in _REQUIRED)


def missing_artifacts() -> list[str]:
    """Human-readable list of artifacts that are still missing."""
    missing = []
    for name, path in config.ARTIFACTS.items():
        if name in ("eval", "roc"):
            continue
        if not path.exists():
            missing.append(f"{name} ({path.name})")
    return missing


def load_predictor() -> PredictorBundle:
    """Load and cache the trained pipeline. Raises ModelNotReadyError if the
    artifacts have not been generated yet."""
    global _cache
    if _cache is not None:
        return _cache

    if not models_available():
        raise ModelNotReadyError(
            "Trained model artifacts are not present. Run "
            "`python scripts/train_models.py` (after placing the survey CSV "
            "in the data/ folder) to generate them."
        )

    import torch  # deferred: heavy dependency, only needed when predicting

    from catboost import CatBoostClassifier
    from modules.core.model_defs import CognitiveImpairmentANN

    meta = config.load_json(config.ARTIFACTS["meta"])

    catboost_model = CatBoostClassifier()
    catboost_model.load_model(str(config.ARTIFACTS["catboost"]))

    checkpoint = torch.load(
        str(config.ARTIFACTS["ann"]), map_location="cpu", weights_only=False
    )
    ann_model = CognitiveImpairmentANN(checkpoint["input_dim"])
    ann_model.load_state_dict(checkpoint["state_dict"])
    ann_model.eval()

    def _unpickle(name: str):
        with open(config.ARTIFACTS[name], "rb") as fh:
            return pickle.load(fh)

    scaler = _unpickle("scaler")
    ann_columns = _unpickle("feature_columns")
    vocab = None
    if config.ARTIFACTS["label_encoder"].exists():
        vocab = _unpickle("label_encoder")

    _cache = PredictorBundle(
        catboost=catboost_model, ann=ann_model, scaler=scaler,
        ann_columns=ann_columns, meta=meta, vocab=vocab,
    )
    return _cache


def reset_cache() -> None:
    """Drop the module-level cache (used after re-training / for tests)."""
    global _cache
    _cache = None


# ------------------------------------------------------------------
# Feature metadata helpers
# ------------------------------------------------------------------
def model_feature_columns() -> list[str]:
    """The exact feature order the model was trained with."""
    meta = config.load_json(config.ARTIFACTS["meta"])
    return meta.get("feature_cols", [])


def category_vocabulary() -> dict[str, list[str]]:
    """Per-feature category vocabulary the model learned (from
    label_encoder.pkl / preprocessing_pipeline.pkl when present)."""
    if config.ARTIFACTS["label_encoder"].exists():
        with open(config.ARTIFACTS["label_encoder"], "rb") as fh:
            vocab = pickle.load(fh)
        return vocab if isinstance(vocab, dict) else {}
    return {}


# ------------------------------------------------------------------
# Prediction — the ONE path used across the whole app
# ------------------------------------------------------------------
def predict(raw_inputs: dict[str, object]) -> RiskResult:
    """Run the real hybrid model on a dict of survey answers.

    Parameters
    ----------
    raw_inputs : dict
        Keys are the model's column names (see metadata.json ``feature_cols``);
        values are the raw categorical labels / numbers. Any missing key is
        treated as the training-time ``"Missing"`` token.

    Returns
    -------
    RiskResult
        Blended probability, prediction, confidence, the individual
        CatBoost / ANN probabilities and per-instance feature contributions.
    """
    bundle = load_predictor()
    meta = bundle.meta
    feature_cols = meta["feature_cols"]
    threshold = float(meta.get("threshold", 0.5))

    row = {col: raw_inputs.get(col, MISSING_TOKEN) for col in feature_cols}
    frame = pd.DataFrame([row], columns=feature_cols).fillna(MISSING_TOKEN)

    # --- Path A: CatBoost (native categorical handling) -------------------
    from catboost import CatBoostClassifier, Pool

    cat_features = meta.get("cat_features", [])
    pool = Pool(frame, cat_features=cat_features)
    cat_proba = float(bundle.catboost.predict_proba(pool)[0][1])

    # Per-instance SHAP contributions (real values from the trained model).
    shap = bundle.catboost.get_feature_importance(pool, type="ShapValues")
    contributions = {col: float(shap[0, i]) for i, col in enumerate(feature_cols)}

    # --- Path B: ANN (one-hot + age-scaling) ------------------------------
    ann_frame = build_ann_frame(frame, cat_features, bundle.scaler, bundle.ann_columns)
    import torch  # deferred
    with torch.no_grad():
        ann_proba = float(bundle.ann(to_tensor_float(ann_frame)).item())

    # --- Ensemble blend (notebook cell: arithmetic mean) ------------------
    hybrid_proba = (cat_proba + ann_proba) / 2.0
    prediction = int(hybrid_proba >= threshold)

    drivers = [
        FeatureDriver(
            feature=readable_driver(col),
            value=str(row[col]),
            contribution=contributions[col],
        )
        for col in feature_cols
    ]
    drivers.sort(key=lambda d: d.magnitude, reverse=True)

    return RiskResult(
        proba_impaired=hybrid_proba,
        cat_proba=cat_proba,
        ann_proba=ann_proba,
        prediction=prediction,
        severity=severity_for(hybrid_proba),
        drivers=drivers[:6],
        threshold=threshold,
        trained_at=str(meta.get("trained_at", "")),
    )
