"""
config.py
=========
Central application configuration for Neuro-Screen.

Holds filesystem paths, brand identity (as published in the thesis report),
risk thresholds, and the reported evaluation results from the conference
paper. Every other module imports constants from here so that values that
must stay consistent (thresholds, column names, model paths) live in one
place only.
"""

from __future__ import annotations

import json
from pathlib import Path

# ------------------------------------------------------------------
# Filesystem layout
# ------------------------------------------------------------------
BASE_DIR = Path(__file__).resolve().parent
ASSETS_DIR = BASE_DIR / "assets"
DATA_DIR = BASE_DIR / "data"
MODELS_DIR = BASE_DIR / "models"

# Trained-model artifacts (generated by scripts/train_models.py).
# ``ann_model.pt`` is a PyTorch checkpoint (state dict + input dim) — the
# notebook's ANN is PyTorch, so the historical ``ann_model.keras`` name from
# the task list does not apply.
ARTIFACTS = {
    "catboost": MODELS_DIR / "catboost_model.cbm",
    "ann": MODELS_DIR / "ann_model.pt",
    "scaler": MODELS_DIR / "scaler.pkl",
    "label_encoder": MODELS_DIR / "label_encoder.pkl",
    "feature_columns": MODELS_DIR / "feature_columns.pkl",
    "preprocessing_pipeline": MODELS_DIR / "preprocessing_pipeline.pkl",
    "meta": MODELS_DIR / "metadata.json",
    "eval": MODELS_DIR / "eval_metrics.json",
    "roc": MODELS_DIR / "roc_data.json",
}

# Candidate locations for the raw survey CSV (the thesis dataset).
DATASET_CANDIDATES = [
    DATA_DIR / "Thesis Dataset.csv",
    DATA_DIR / "Detection of cognitive impairment in insomniac university students dataset.csv",
    DATA_DIR / "dataset.csv",
    DATA_DIR / "neuro_screen_survey.csv",
]

# Feature schema used by the assessment UI. scripts/train_models.py writes
# an authoritative, CSV-derived schema to FEATURE_SCHEMA_GENERATED when the
# real dataset is present.
FEATURE_SCHEMA = DATA_DIR / "feature_schema.json"
FEATURE_SCHEMA_GENERATED = DATA_DIR / "feature_schema.generated.json"

REPORTED_RESULTS = DATA_DIR / "reported_results.json"

# ------------------------------------------------------------------
# Brand identity (from the thesis report cover + approval page)
# ------------------------------------------------------------------
BRAND = {
    "name": "Neuro-Screen",
    "subtitle": ("Hybrid Ensemble Framework for Early Detection of Cognitive "
                 "Impairment in Insomniac University Students"),
    "institution": "American International University-Bangladesh (AIUB)",
    "faculty": "Faculty of Science and Technology",
    "department": "Department of Computer Science",
    "course": "CSC 4298 — Thesis/Project",
    "semester": "Spring 2025-2026",
    "submission_date": "30 July, 2026",
    "thesis_group": "G52",
    "authors": [
        {"name": "Sajidur Rahman Sajid", "id": "22-49076-3"},
        {"name": "Khadija Akter", "id": "22-48295-3"},
        {"name": "Md Iqramul Kabir", "id": "22-46165-1"},
        {"name": "Shahadat Hossain Gazi", "id": "22-48095-2"},
    ],
}

# ------------------------------------------------------------------
# Risk thresholds
# ------------------------------------------------------------------
# Decision threshold from the notebook: hybrid prediction = label 1 when
# P(impaired) >= 0.5. Severity bands are for the UI risk meter only.
RISK = {
    "decision_threshold": 0.5,
    "low_max": 0.35,
    "moderate_max": 0.55,
    "labels": ("Low Risk", "Moderate Risk", "High Risk"),
}


# ------------------------------------------------------------------
# Small JSON helpers
# ------------------------------------------------------------------
def load_json(path: Path):
    """Load a JSON file as a dict (returns {} on any failure)."""
    try:
        with open(path, "r", encoding="utf-8") as fh:
            return json.load(fh)
    except (OSError, ValueError):
        return {}


def save_json(path: Path, payload) -> None:
    """Serialize a dict/list to JSON (ensuring the parent dir exists)."""
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8") as fh:
        json.dump(payload, fh, indent=2, ensure_ascii=False)


def load_feature_schema() -> list[dict]:
    """Return the authoritative feature schema for the assessment UI.

    Prefers the CSV-derived schema written by scripts/train_models.py; falls
    back to the shipped best-effort schema otherwise.
    """
    path = FEATURE_SCHEMA_GENERATED if FEATURE_SCHEMA_GENERATED.exists() else FEATURE_SCHEMA
    data = load_json(path)
    return data.get("features", []) if isinstance(data, dict) else []
